name: APK Uretici
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Java Ayarla
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Sahte Keystore Olustur
        run: |
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

      - name: Gradle Kur
        uses: gradle/actions/setup-gradle@v4

      - name: APK Hazırla
        run: gradle assembleDebug

      - name: APKyi Yukle
        uses: actions/upload-artifact@v4
        with:
          name: standoff2-uygulamam
          path: app/build/outputs/apk/debug/app-debug.apk
